📦
450 /agent/index.js
528 /agent/common/StdString.js
158 /agent/logger.js
1710 /agent/nativefunctions.js
✄
import{log as n}from"./logger.js";import{StdString as t}from"./common/StdString.js";import{CustomNativeFunction as e}from"./nativefunctions.js";let o=!0;Interceptor.attach(e.ccGLRenderScenePointer,{onEnter:function(n){if(o){o=!1;var t=n[0].readPointer();console.log("currentScene: "+t),e.nativeHook()}},onLeave:function(n){}}),Interceptor.attach(e.ccSpriteCreatePointer,{onEnter:function(e){n(new t(e[0]).getStdString()??"")},onLeave:function(n){}});
✄
export class StdString{constructor(r){this.addr=r}get bufAddr(){return this.reservedSize.compare(16)>0?this.addr.readPointer():this.addr}get size(){return this.addr.add(16).readPointer()}get reservedSize(){return this.addr.add(16).add(Process.pointerSize).readPointer()}toString(){const r=this.size;return r.isNull()?"<EMPTY std::string>":this.bufAddr.readCString(r.toInt32())}getStdString(){return 0==(1&this.addr.readU8())?this.addr.add(1).readUtf8String():this.addr.add(2*Process.pointerSize).readPointer().readUtf8String()}}
✄
import{CustomNativeFunction as o}from"./nativefunctions.js";export function log(o){console.log(o)}export function cclog(c){o.cclog(Memory.allocUtf8String(c))}
✄
var e;export class CustomNativeFunction{}e=CustomNativeFunction,CustomNativeFunction.libName="libMyGame.so",CustomNativeFunction.libNativeName="libnativehook.so",CustomNativeFunction.nativeHookPointer=Module.findExportByName(e.libNativeName,"nativehook")??new NativePointer(0),CustomNativeFunction.getStdStringRefPointer=Module.findExportByName(e.libNativeName,"getStdStringRef")??new NativePointer(0),CustomNativeFunction.cclogPointer=Module.findExportByName(e.libName,"_ZN7cocos2d3logEPKcz")??new NativePointer(0),CustomNativeFunction.ccGetVersionPointer=Module.findExportByName(e.libName,"_ZN7cocos2d14cocos2dVersionEv")??new NativePointer(0),CustomNativeFunction.ccSpriteCreatePointer=Module.findExportByName(e.libName,"_ZN7cocos2d6Sprite6createERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE")??new NativePointer(0),CustomNativeFunction.ccGLRenderScenePointer=Module.getExportByName(e.libName,"_ZN7cocos2d6GLView11renderSceneEPNS_5SceneEPNS_8RendererE")??new NativePointer(0),CustomNativeFunction.ccNodeAddChildPointer=Module.findExportByName(e.libName,"_ZN7cocos2d4Node8addChildEPS0_i")??new NativePointer(0),CustomNativeFunction.cclog=new NativeFunction(e.cclogPointer,"void",["pointer"]),CustomNativeFunction.ccGetVerion=new NativeFunction(e.ccGetVersionPointer,"pointer",[]),CustomNativeFunction.ccSpriteCreate=new NativeFunction(e.ccSpriteCreatePointer,"pointer",["pointer"]),CustomNativeFunction.ccNodeAddChild=new NativeFunction(e.ccNodeAddChildPointer,"uint",["pointer","pointer","int"]),CustomNativeFunction.getStdStringRef=new NativeFunction(e.getStdStringRefPointer,"pointer",["pointer"]),CustomNativeFunction.nativeHook=new NativeFunction(e.nativeHookPointer,"void",[]);